# Generated by Django 2.2 on 2019-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasa',
            name='cykl_przeg',
            field=models.CharField(choices=[('1', 'Roczny'), ('2', 'Dwutletni')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='ostatni_przeg',
            field=models.DateField(blank=True, null=True),
        ),
    ]
