# Generated by Django 2.2 on 2019-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podatnik',
            name='nip',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
