# Generated by Django 2.2.1 on 2019-06-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urzad_skarbowy',
            name='nr_urzedu',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='przeglad',
            name='ilosc_raportow',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
