# Generated by Django 2.2 on 2019-05-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0002_auto_20190521_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasa',
            old_name='ostatni_przeg',
            new_name='nastepny_przeg',
        ),
        migrations.AlterField(
            model_name='kasa',
            name='cykl_przeg',
            field=models.CharField(choices=[('1', 'Roczny'), ('2', 'Dwuletni')], max_length=10),
        ),
    ]
