# Generated by Django 2.2 on 2019-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0002_auto_20190525_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podatnik',
            name='nazwa_cd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
