# Generated by Django 2.2.2 on 2019-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0003_auto_20190605_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='przeglad',
            name='faktura',
            field=models.BooleanField(default=False),
        ),
    ]
