# Generated by Django 2.2.1 on 2019-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0004_przeglad_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przeglad',
            name='info',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
