# Generated by Django 2.2 on 2019-05-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0006_auto_20190529_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasa',
            name='miejsce_inst',
            field=models.CharField(default='j.w.', max_length=60),
        ),
    ]
