# Generated by Django 2.2 on 2019-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasy', '0007_kasa_miejsce_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='przeglad',
            name='ilosc_raportow',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kasa',
            name='cykl_przeg',
            field=models.CharField(choices=[('1', 'Roczny'), ('2', 'Dwuletni')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='kasa',
            name='miejsce_inst',
            field=models.CharField(default='siedziba firmy', max_length=60),
        ),
    ]
